### ISSUE TITLE
Create a programmatic API

### ISSUE THREAD

**Issue by unscriptable** [cujojs/cram#19]
So that cram can be used in a rails asset pipeline or from a Java build (without using a shell), cram needs a programmatic API.  I am thinking that it's very likely that all of the options of the CLI API will be needed by a programmatic API, so I think it's worth some time to expose the CLI API in Javascript.  

Any other thoughts, @jeremyg484 ?

**Comment by gihrig** [comment]
I have a Java project that needs asset optimization at build time, and I'm considering Cram. I'm also considering migrating parts of the project to Node. Given this mix of technologies and the inevitable change over time, a programatic API sounds useful.

**Comment by unscriptable** [comment]
Noted, @gihrig! :)

**Comment by snichme** [comment]
:+1:

**Comment by unscriptable** [comment]
This has finally landed in the dev branch and will be released shortly in 0.8.0.

**Comment by briancavalier** [comment]
Woot!
