### ISSUE TITLE
cram should not output the moduleLoader's prefix to the bundle

### ISSUE THREAD

**Issue by unscriptable** [cujojs/cram#25]
In short: cram should output `define("backbone/backbone", ...` not `define("curl/loader/cjsm11!backbone/backbone"...` as a plugin would.  curl/cram module loaders are plugins that are used implicitly, but need to output normal-looking modules.

Plugins always prefix their compiled resources with the plugin id.  This is so that a dev can request the same resource at run-time (from outside the bundle, for instance), and it will match.

On the other hand, CJS modules are supposed to be loaded transparently (no explicit module id) so the plugin id should be left out.  I guess I hadn't thought this through, yet.  This makes sense to me. 

Also: ES6 module loaders will allow cross-compiled ("transpiled") modules and will likely work similarly (the module loaders won't have to be explicit).

**Comment by gehan** [comment]
This should fix it! https://github.com/cujojs/cram/pull/26

**Comment by unscriptable** [comment]
Closed by #26.  Thanks Gehan!
