### ISSUE TITLE
Unclear how to use wire/cram/builder.js

### ISSUE THREAD

**Issue by dizzib** [cujojs/cram#3]
What's New on wire.js states...

0.6.0
Experimental optimizer/build tool support for cram. Point cram at your wire spec and let it optimize your entire app! Docs coming soon

This sounds awesome but I can't find any docs/examples and it's not obvious, so any hints much appreciated!

Ta,
Andy.

**Comment by briancavalier** [comment]
Hey @dizzib,

What versions of wire and curl are you using currently?

This feature is probably in an unstable state with the latest versions of wire and curl (hence the "Experimental").  We're currently refactoring cram and wire's builder plugin, so there will be updated build support soon, along with documentation.  Once wire v0.8.0 final is released, we'll be targeting a follow-on release for the updated cram build support.

Let's leave this issue open so we don't get lazy on the documentation :)

**Comment by dizzib** [comment]
Hi Brian, sounds good!

fwiw I'm on wire 0.7.5, curl 0.6.2 and cram 0.6.

And I'd be happy to help test your experimental code on my app anytime, just let me know. Cheers!

**Comment by briancavalier** [comment]
Cool, thanks for the offer! Hopefully we can take you up on it :)

**Comment by unscriptable** [comment]
I'm getting back on cram.js 0.6 as soon as I can get curl.js 0.6.3 released (which should be this week).

**Comment by unscriptable** [comment]
@dizzib: cram.js is third on the priority list right now (and the other two items are mostly done).  Should start working on it later this week.  -- John

**Comment by dizzib** [comment]
Great, thanks! :-)

**Comment by AnAppAMonth** [comment]
I'd also like to see an example on this. These are great tools, but seriously lacking in documentation.
