### ISSUE TITLE
Postinstall of Bower dependencies breaks with sudo

### ISSUE THREAD

**Issue by phated** [cujojs/cram#32]
When running `sudo npm install cram`, the command errors with:

```
npm http GET https://registry.npmjs.org/cram
npm http 304 https://registry.npmjs.org/cram

> cram@0.7.6 postinstall /Users/phated/test/node_modules/cram
> bower install

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
npm ERR! weird error 1
npm ERR! not ok code 0
```

I think the Bower install should happen on prepublish, as per https://npmjs.org/doc/misc/npm-scripts.html#NOTE-INSTALL-SCRIPTS-ARE-AN-ANTIPATTERN

**Comment by unscriptable** [comment]
Thanks @phated.  Even though "prepublish" (the word) makes no sense to me, that seems like the correct thing to do.

**Comment by phated** [comment]
It looks like your `.gitignore` has `amd_modules/` in it.  If you don't have a `.npmignore`, npm uses the `.gitignore` to generate it, so `amd_modules/` isn't in the installed package.

**Comment by phated** [comment]
You should be able to use `npm pack` to test the prepublish command and then unzip to make sure it has everything.

**Comment by unscriptable** [comment]
amd_modules is ignored on purpose. the prepublish script should install them. isn't that working on your machine?

**Comment by phated** [comment]
prepublish happens when you publish the module.  prepublish will be executed and amd_modules included in the zip file stored in NPM.

**Comment by unscriptable** [comment]
this conversation is confusing me! :)

if we don't want to publish amd_modules, we want them to be installed at `npm install` time, what is the correct method? cc @bcavalier @scothis

**Comment by phated** [comment]
The correct method is to not rely on the bower install and use github urls in the NPM dependencies.

**Comment by scothis** [comment]
I'm confused as to why you're using bower to fetch dependencies for an npm package... Why not just use npm's dependency resolution?

**Comment by phated** [comment]
Why are you against bundling the bower dependencies in the npm published package?

To test the npm package, you can run `npm pack`
