### ISSUE TITLE
amd_modules folder missing after installing cram from npm

### ISSUE THREAD

**Issue by jsedlacek** [cujojs/cram#33]
When I install cram using npm the amd_modules folder is missing.

```
$ npm install -g cram
$ cram run.js
cram failed:  Cannot find module 'xxx/cram/amd_modules/curl/src/curl/../../dist/curl-for-ssjs/curl.js'
```

After running `bower install` in cram folder everything works fine.

**Comment by unscriptable** [comment]
Thanks @jsedlacek!

What version of node and npm are you using?

**Comment by jsedlacek** [comment]
```
$ node --version
v0.10.21
$ npm --version
1.3.11
```

**Comment by unscriptable** [comment]
Hm, thats very recent. I wonder why it works on some machines (like mine :) ).  I'll keep digging.

**Comment by phated** [comment]
This is related to the #32 issue that you published.  It broke because prepublish installs locally and then publishes to NPM. Since you are gitignoring amd_modules, they don't get published.

It works locally because you have the bower modules.
