### ISSUE TITLE
cram thinks the `require()`s in rest/mime/registry are global

### ISSUE THREAD

**Issue by unscriptable** [cujojs/cram#38]
cram's scan module thinks the `require()`s in rest/mime/registry are global:
https://github.com/cujojs/rest/blob/master/mime/registry.js#L116-L117

As a result, these modules are not included in the bundle.

**Comment by gogamoga** [comment]
And the hack-fix: https://gist.github.com/gogamoga/9541651

**Comment by unscriptable** [comment]
RegExp parsing code pulls in a bit extra to determine the difference between the division symbol and RegExp literals.  It pulls in an extra open parenthesis with this snippet: `mime.split(/[;\+]/)` but didn't account for it.  It now accounts for any captured parens.

**Comment by gogamoga** [comment]
This commit has solved the issue completely! Thanks again.
