### ISSUE TITLE
rewrite to use curl.js internally

### ISSUE THREAD

**Issue by unscriptable** [cujojs/cram#4]
This issue is to track the total rewrite of cram.js using curl.js internally.  

We've already got curl.js working in node.js and ringojs, we just need to finish the logic around configuration, dependency analysis, and concatenation.

**Comment by jbadeau** [comment]
What version of node are you using?

**Comment by unscriptable** [comment]
v0.8.10

**Comment by unscriptable** [comment]
This has been pushed to master
