### ISSUE TITLE
Empty multi-line array of dependecies causes error.

### ISSUE THREAD

**Issue by fedevegili** [cujojs/cram#40]
If you define a module with an empty array of dependencies, like this:

//causes bug
define([
    ], function() {});

//process OK
define([], function() {});

Cram.js throws the following error:

cram failed:  ENOENT, open 'C:\sesuite\1.4\web\wwwroot\ui\desktop\lite\resources
\js\
    .js'
Error: ENOENT, open 'C:\sesuite\1.4\web\wwwroot\ui\desktop\lite\resources\js\
    .js'

**Comment by unscriptable** [comment]
Hey @fedevegili,  this is fixed in the dev branch.  Feel free to try it if you have a minute. Thanks!  -- John
